landing.tests.test_logic.YourTestClass Class Reference
Public Member Functions
def setUp (self)
def tearDown (self)
def test_emailFound (self)
def test_generate_new_semester (self)
def test_generateConcentrationsDD (self)
def test_generateDiplomaDD (self)
def test_generateMajorDD (self)
def test_generateMinorDD (self)
def test_get_semester_by_month_year (self)
def test_getDegree (self)
def test_getUserByEmail (self)
def test_is_full (self)
def test_removeCoursesTaken (self)
Detailed Description
Definition at line 10 of file test_logic.py.
Member Function Documentation
setUp()
def landing.tests.test_logic.YourTestClass.setUp (self)
Definition at line 12 of file test_logic.py.
tearDown()
def landing.tests.test_logic.YourTestClass.tearDown (self)
Definition at line 16 of file test_logic.py.
test_emailFound()
def landing.tests.test_logic.YourTestClass.test_emailFound (self)
@test_emailFound stores a user into the database and checks that the email is found in the database
@param self references current instance of the class
Definition at line 478 of file test_logic.py.
References landing.views.emailFound().
test_generate_new_semester()
def landing.tests.test_logic.YourTestClass.test_generate_new_semester (self)
@test_generate_new_semester tests if a semester is created and stored correctly
@param self references current instance of the class
Definition at line 360 of file test_logic.py.
References landing.views.generateNewSemester(), and landing.views.getSemesterByMonthYear().
test_generateConcentrationsDD()
def landing.tests.test_logic.YourTestClass.test_generateConcentrationsDD (self)
@test_generateConcentrationsDD creates a list of possible concentrations for use on the createuser page
@param self references current instance of the class
Definition at line 448 of file test_logic.py.
References landing.views.generateConcentrationsDD().
test_generateDiplomaDD()
def landing.tests.test_logic.YourTestClass.test_generateDiplomaDD (self)
@test_generateDiplomaDD creates a list of possible diplomas for use on the createuser page
@param self references current instance of the class
Definition at line 461 of file test_logic.py.
References landing.views.generateDiplomaDD().
test_generateMajorDD()
def landing.tests.test_logic.YourTestClass.test_generateMajorDD (self)
@test_generateMajorDD creates a list of possible majors for use on the createuser page
@param self references current instance of the class
Definition at line 414 of file test_logic.py.
References landing.views.generateMajorDD().
test_generateMinorDD()
def landing.tests.test_logic.YourTestClass.test_generateMinorDD (self)
@test_generateMinorDD creates a list of possible minors for use on the createuser page
@param self references current instance of the class
Definition at line 434 of file test_logic.py.
References landing.views.generateMinorDD().
test_get_semester_by_month_year()
def landing.tests.test_logic.YourTestClass.test_get_semester_by_month_year (self)
@test_get_semester_by_month_year tests if the correct semester is calculated
@param self references current instance of the class
Definition at line 343 of file test_logic.py.
References landing.views.getSemesterByMonthYear().
test_getDegree()
def landing.tests.test_logic.YourTestClass.test_getDegree (self)
@test_getDegree creates a degree object and checks that the degree is stored in the SQLite3 database
@param self references current instance of the class
Definition at line 215 of file test_logic.py.
References landing.views.getDegree().
test_getUserByEmail()
def landing.tests.test_logic.YourTestClass.test_getUserByEmail (self)
    @test_getUserByEmail creates a user account and checks that the account is stored in the SQLite3 database
    @param self references current instance of the class
    @var email sample username string to store in SQLite3 database
    @var p  sample password string to store in SQLite3 database
Definition at line 195 of file test_logic.py.
References landing.views.getUserByEmail().
test_is_full()
def landing.tests.test_logic.YourTestClass.test_is_full (self)
@test_is_full tests if the semester has hit the maximum number of credits allowable
@param self references current instance of the class
Definition at line 379 of file test_logic.py.
References landing.views.generateNewSemester(), landing.views.getSemesterByMonthYear(), and landing.views.isFull().
test_removeCoursesTaken()
def landing.tests.test_logic.YourTestClass.test_removeCoursesTaken (self)
@test_removeCoursesTaken tests the correctness of the computed list of classes a user still needs to take in order to graduate
@param self references current instance of the class
Definition at line 271 of file test_logic.py.
References landing.views.removeCoursesTaken().
The documentation for this class was generated from the following file:
mavAgenda/landing/tests/test_logic.py