landing.views Namespace Reference
Functions
def checkCourseValid (course, classesTaken, semesterCourses, ssf)
def checkOfferedSemester (course, ssf)
def checkPrereqsMet (preqreqs, classesTaken, currentSemester)
def createSchedule (uID)
def createuser (request)
def emailFound (email)
def generateCheckBoxEntities (uID)
def generateConcentrationsDD ()
def generateDiplomaDD ()
def generateMajorDD ()
def generateMinorDD ()
def generateNewSemester (semester)
def generateYearDD ()
def getCompletedByUser (uID)
def getCoursesForUser (uID)
def getDegree (diploma, type, track)
def getDegreeReqs (degrees)
def getSemesterByMonthYear (m)
def getUserByEmail (e)
def isFull (courseList)
def login (request)
def nextsemesterpreferences (request, pk)
def removeCoursesTaken (requiredClasses, classesTaken)
def removeUserCompletedEnteries (uID)
def saveClassesToUser (classesChecked, uID)
def schedule (request, pk)
def selectcourses (request, pk)
Function Documentation
checkCourseValid()
def landing.views.checkCourseValid (course, classesTaken, semesterCourses, ssf)
@checkCourseValid determines if a given Course can be taken during a given semester
@param course: the Course under test
@param classesTaken: a list of Course (objects) that the User has already completed
@parm scheduledClasses: a list of Course (objects) the scheduling algorithm has accounted for already
@param ssf: the Spring, Summer, Fall, offering attribute of the Course
Definition at line 106 of file views.py.
References landing.views.checkOfferedSemester(), and landing.views.checkPrereqsMet().
Referenced by landing.views.createSchedule().
checkOfferedSemester()
def landing.views.checkOfferedSemester (course, ssf)
@checkOfferedSemester determines if a given Course if offered during the current semester
@param course: the Course under test
@param ssf: the Spring, Summer, Fall, offering attribute of the Course
Definition at line 95 of file views.py.
Referenced by landing.views.checkCourseValid().
checkPrereqsMet()
def landing.views.checkPrereqsMet (preqreqs, classesTaken, currentSemester)
@checkPrereqsMet determines if the User has met all Prereqs for a particular Course
@param prereqs: a list of Course (objects) corresponding to Prereqs for a given Course
@param classesTaken: a list of Course (objects) that the User has already completed
@parm currentSemester: a list of Course (objects) the scheduling algorithm has accounted for already
Definition at line 76 of file views.py.
Referenced by landing.views.checkCourseValid().
createSchedule()
def landing.views.createSchedule (uID)
@createSchedule generates semester-by-semester schedule for User's needed Courses according to Degree
@param uID: primary key associated with active user
Definition at line 168 of file views.py.
References landing.views.checkCourseValid(), landing.views.generateNewSemester(), landing.views.getCompletedByUser(), landing.views.getCoursesForUser(), landing.views.getSemesterByMonthYear(), landing.views.isFull(), and landing.views.removeCoursesTaken().
Referenced by landing.views.schedule().
createuser()
def landing.views.createuser (request)
@createuser send a request to render the createuser.html page
@param request: generates the response
Definition at line 374 of file views.py.
References landing.views.emailFound(), landing.views.generateConcentrationsDD(), landing.views.generateDiplomaDD(), landing.views.generateMajorDD(), landing.views.generateMinorDD(), and landing.views.getDegree().
emailFound()
def landing.views.emailFound (email)
@emailFound provides feedback if the email is already in the User database table
@param email: email under test
Definition at line 313 of file views.py.
Referenced by landing.views.createuser(), landing.views.login(), and landing.tests.test_logic.YourTestClass.test_emailFound().
generateCheckBoxEntities()
def landing.views.generateCheckBoxEntities (uID)
@generateCheckBoxEntities creates a list of tuples of requirements, course names and numbers for the selectcourses page
@param uID: primary key corresponding to the active user
Definition at line 233 of file views.py.
References landing.views.getDegreeReqs().
Referenced by landing.views.selectcourses().
generateConcentrationsDD()
def landing.views.generateConcentrationsDD ()
@generateConcentrationsDD creates a list of possible concentrations for use on the createuser page
Definition at line 278 of file views.py.
Referenced by landing.views.createuser(), and landing.tests.test_logic.YourTestClass.test_generateConcentrationsDD().
generateDiplomaDD()
def landing.views.generateDiplomaDD ()
@generateDiplomaDD creates a list of possible diplomas for use on the createuser page
Definition at line 289 of file views.py.
Referenced by landing.views.createuser(), and landing.tests.test_logic.YourTestClass.test_generateDiplomaDD().
generateMajorDD()
def landing.views.generateMajorDD ()
@generateMajorDD creates a list of possible majors for use on the createuser page
Definition at line 256 of file views.py.
Referenced by landing.views.createuser(), and landing.tests.test_logic.YourTestClass.test_generateMajorDD().
generateMinorDD()
def landing.views.generateMinorDD ()
@generateMinorDD creates a list of possible minors for use on the createuser page
Definition at line 267 of file views.py.
Referenced by landing.views.createuser(), and landing.tests.test_logic.YourTestClass.test_generateMinorDD().
generateNewSemester()
def landing.views.generateNewSemester (semester)
@generateNewSemester creates a new logical semester
@param semester: previous semester list
Definition at line 135 of file views.py.
Referenced by landing.views.createSchedule(), landing.tests.test_logic.YourTestClass.test_generate_new_semester(), and landing.tests.test_logic.YourTestClass.test_is_full().
generateYearDD()
def landing.views.generateYearDD ()
@generateYearDD creates a list of upcoming years for use on the createuser page
Definition at line 300 of file views.py.
Referenced by landing.views.nextsemesterpreferences().
getCompletedByUser()
def landing.views.getCompletedByUser (uID)
@getCompletedByUser provides a list of Course (objects) the user has taken
@param uID: the primary key corresponding to the active user
Definition at line 35 of file views.py.
Referenced by landing.views.createSchedule().
getCoursesForUser()
def landing.views.getCoursesForUser (uID)
@getCoursesForUser provides a list of Course (objects) the user must complete for their respective Degree
@param uID: the primary key corresponding to the active user
Definition at line 46 of file views.py.
Referenced by landing.views.createSchedule().
getDegree()
def landing.views.getDegree (diploma, type, track)
@getDegree searches the Degree table to find the Degree object with corresponding degree and major
@param diploma: degree attribute of Degree being searched for (bachelors, masters, doctorate)
@param type: degree attribute of Degree being searched for (science, art)
@param track: major attribute of Degree being searched for (computer science, MIS, etc)
Definition at line 23 of file views.py.
Referenced by landing.views.createuser(), and landing.tests.test_logic.YourTestClass.test_getDegree().
getDegreeReqs()
def landing.views.getDegreeReqs (degrees)
@getDegreeRegs returns a list of requirements for all degrees a user has selected
@param degrees: a list of degrees associated with the user
Definition at line 221 of file views.py.
Referenced by landing.views.generateCheckBoxEntities().
getSemesterByMonthYear()
def landing.views.getSemesterByMonthYear (m)
@getSemesterByMonthYear determines semester (Spring, Summer, Fall) according to current month
@param m: current month
Definition at line 122 of file views.py.
Referenced by landing.views.createSchedule(), landing.tests.test_logic.YourTestClass.test_generate_new_semester(), landing.tests.test_logic.YourTestClass.test_get_semester_by_month_year(), and landing.tests.test_logic.YourTestClass.test_is_full().
getUserByEmail()
def landing.views.getUserByEmail (e)
@getUserByEmail searches the User table to find the User object with a corresponding email
@param e: the email being searched for
Definition at line 13 of file views.py.
Referenced by landing.views.login(), and landing.tests.test_logic.YourTestClass.test_getUserByEmail().
isFull()
def landing.views.isFull (courseList)
@isFull determines if a semester has hit the maximum number of credits allowable
@param courseList: list of Course (objects) the user is scheduled to take during current semester
Definition at line 155 of file views.py.
Referenced by landing.views.createSchedule(), and landing.tests.test_logic.YourTestClass.test_is_full().
login()
def landing.views.login (request)
@login send a request to render the login.html page
@param request: generates the response
Definition at line 357 of file views.py.
References landing.views.emailFound(), and landing.views.getUserByEmail().
nextsemesterpreferences()
def landing.views.nextsemesterpreferences (request, pk)
@nextsemesterpreferences send a request to render the nextsemesterpreferences.html page
@param request: generates the response
@param pk: primary key corresponding to active user
Definition at line 465 of file views.py.
References landing.views.generateYearDD().
removeCoursesTaken()
def landing.views.removeCoursesTaken (requiredClasses, classesTaken)
@removeCoursesTaken provides a list of Course (objects) the user must still take (required, but not completed classes)
@param requiredClasses: a list of Course (objects) required for the User's Degree
@param classesTaken: a list of Course (objects) that the User has already completed
Definition at line 64 of file views.py.
Referenced by landing.views.createSchedule(), and landing.tests.test_logic.YourTestClass.test_removeCoursesTaken().
removeUserCompletedEnteries()
def landing.views.removeUserCompletedEnteries (uID)
@removeUserCompletedEntries updates database to remove courses completed from a particular user
@param uID: pk of the associated active user
Definition at line 342 of file views.py.
Referenced by landing.views.selectcourses().
saveClassesToUser()
def landing.views.saveClassesToUser (classesChecked, uID)
@saveClassesToUser updates database with a list of the user has taken
@param classesChecked: list of courses the user specified as having taken
@param uID: pk of the associated active user
Definition at line 325 of file views.py.
Referenced by landing.views.selectcourses().
schedule()
def landing.views.schedule (request, pk)
@schedule send a request to render the schedule.html page
@param request: generates the response
@param pk: primary key corresponding to active user
Definition at line 483 of file views.py.
References landing.views.createSchedule().
selectcourses()
def landing.views.selectcourses (request, pk)
@selectcourses send a request to render the selectcourses.html page
@param request: generates the response
@param pk: primary key corresponding to active user
Definition at line 449 of file views.py.
References landing.views.generateCheckBoxEntities(), landing.views.removeUserCompletedEnteries(), and landing.views.saveClassesToUser().