mavAgenda.landing.tests.test_logic.YourTestClass Class Reference
Public Member Functions
def setUp (self)
def tearDown (cself)
def test_emailFound (self)
def test_generate_new_semester (self)
def test_generateConcentrationsDD (self)
def test_generateDiplomaDD (self)
def test_generateMajorDD (self)
def test_generateMinorDD (self)
def test_get_semester_by_month_year (self)
def test_getDegree (self)
def test_getUserByEmail (self)
def test_is_full (self)
def test_removeCoursesTaken (self)
def test_removeUserCompletedEnteries (self)
Detailed Description
Definition at line 7 of file test_logic.py.
Member Function Documentation
setUp()
def mavAgenda.landing.tests.test_logic.YourTestClass.setUp (self)
Definition at line 9 of file test_logic.py.
tearDown()
def mavAgenda.landing.tests.test_logic.YourTestClass.tearDown (cself)
Definition at line 13 of file test_logic.py.
test_emailFound()
def mavAgenda.landing.tests.test_logic.YourTestClass.test_emailFound (self)
Definition at line 431 of file test_logic.py.
References mavAgenda.landing.views.emailFound().
test_generate_new_semester()
def mavAgenda.landing.tests.test_logic.YourTestClass.test_generate_new_semester (self)
Definition at line 338 of file test_logic.py.
References mavAgenda.landing.views.generateNewSemester().
test_generateConcentrationsDD()
def mavAgenda.landing.tests.test_logic.YourTestClass.test_generateConcentrationsDD (self)
Definition at line 409 of file test_logic.py.
References mavAgenda.landing.views.generateConcentrationsDD().
test_generateDiplomaDD()
def mavAgenda.landing.tests.test_logic.YourTestClass.test_generateDiplomaDD (self)
Definition at line 418 of file test_logic.py.
References mavAgenda.landing.views.generateDiplomaDD().
test_generateMajorDD()
def mavAgenda.landing.tests.test_logic.YourTestClass.test_generateMajorDD (self)
Definition at line 385 of file test_logic.py.
References mavAgenda.landing.views.generateMajorDD().
test_generateMinorDD()
def mavAgenda.landing.tests.test_logic.YourTestClass.test_generateMinorDD (self)
Definition at line 400 of file test_logic.py.
References mavAgenda.landing.views.generateMinorDD().
test_get_semester_by_month_year()
def mavAgenda.landing.tests.test_logic.YourTestClass.test_get_semester_by_month_year (self)
Definition at line 325 of file test_logic.py.
test_getDegree()
def mavAgenda.landing.tests.test_logic.YourTestClass.test_getDegree (self)
Definition at line 206 of file test_logic.py.
References mavAgenda.landing.views.getDegree().
test_getUserByEmail()
def mavAgenda.landing.tests.test_logic.YourTestClass.test_getUserByEmail (self)
Definition at line 192 of file test_logic.py.
References mavAgenda.landing.views.getUserByEmail().
test_is_full()
def mavAgenda.landing.tests.test_logic.YourTestClass.test_is_full (self)
Definition at line 353 of file test_logic.py.
References mavAgenda.landing.views.generateNewSemester().
test_removeCoursesTaken()
def mavAgenda.landing.tests.test_logic.YourTestClass.test_removeCoursesTaken (self)
Definition at line 257 of file test_logic.py.
References mavAgenda.landing.views.removeCoursesTaken().
test_removeUserCompletedEnteries()
def mavAgenda.landing.tests.test_logic.YourTestClass.test_removeUserCompletedEnteries (self)
Definition at line 487 of file test_logic.py.
The documentation for this class was generated from the following file:
C:/Users/lauren/PycharmProjects/MavLinkMadeEasy/mavAgenda/landing/tests/test_logic.py