mavAgenda.CSVPreprocessing Namespace Reference
Functions
def read_course_csv ()
def read_credit_csv ()
def read_csvs ()
def read_from_file ()
def read_reqs_csv ()
Variables
dictionary buildings_to_campuses
centerStreet = Campus(campus_name='B')
dictionary course_id_to_course = {}
string course_path = '\\landing\\degreeData\\Class List.csv'
string credits_path = '\\landing\\degreeData\\Course Credits.csv'
friday = Weekday(weekday_name='F')
monday = Weekday(weekday_name='M')
north = Campus(campus_name='N')
placeholder_instructor = Instructor(instructor_firstName='John', instructor_lastName='Smith')
remote = Campus(campus_name='R')
string reqs_path = '\\landing\\degreeData\\Course Requirements.csv'
saturday = Weekday(weekday_name='S')
dictionary semesters
south = Campus(campus_name='S')
sunday = Weekday(weekday_name='U')
thursday = Weekday(weekday_name='R')
tuesday = Weekday(weekday_name='T')
wednesday = Weekday(weekday_name='W')
Function Documentation
read_course_csv()
def mavAgenda.CSVPreprocessing.read_course_csv ()
Definition at line 155 of file CSVPreprocessing.py.
Referenced by mavAgenda.CSVPreprocessing.read_csvs().
read_credit_csv()
def mavAgenda.CSVPreprocessing.read_credit_csv ()
Definition at line 275 of file CSVPreprocessing.py.
Referenced by mavAgenda.CSVPreprocessing.read_csvs().
read_csvs()
def mavAgenda.CSVPreprocessing.read_csvs ()
Definition at line 143 of file CSVPreprocessing.py.
References mavAgenda.CSVPreprocessing.read_course_csv(), mavAgenda.CSVPreprocessing.read_credit_csv(), and mavAgenda.CSVPreprocessing.read_reqs_csv().
read_from_file()
def mavAgenda.CSVPreprocessing.read_from_file ()
Definition at line 284 of file CSVPreprocessing.py.
read_reqs_csv()
def mavAgenda.CSVPreprocessing.read_reqs_csv ()
Definition at line 310 of file CSVPreprocessing.py.
Referenced by mavAgenda.CSVPreprocessing.read_csvs().
Variable Documentation
buildings_to_campuses
dictionary mavAgenda.CSVPreprocessing.buildings_to_campuses
Definition at line 22 of file CSVPreprocessing.py.
centerStreet
mavAgenda.CSVPreprocessing.centerStreet = Campus(campus_name='B')
Definition at line 87 of file CSVPreprocessing.py.
course_id_to_course
dictionary mavAgenda.CSVPreprocessing.course_id_to_course = {}
Definition at line 133 of file CSVPreprocessing.py.
course_path
string mavAgenda.CSVPreprocessing.course_path = '\\landing\\degreeData\\Class List.csv'
Definition at line 14 of file CSVPreprocessing.py.
credits_path
string mavAgenda.CSVPreprocessing.credits_path = '\\landing\\degreeData\\Course Credits.csv'
Definition at line 15 of file CSVPreprocessing.py.
friday
mavAgenda.CSVPreprocessing.friday = Weekday(weekday_name='F')
Definition at line 75 of file CSVPreprocessing.py.
monday
mavAgenda.CSVPreprocessing.monday = Weekday(weekday_name='M')
Definition at line 67 of file CSVPreprocessing.py.
north
mavAgenda.CSVPreprocessing.north = Campus(campus_name='N')
Definition at line 83 of file CSVPreprocessing.py.
placeholder_instructor
mavAgenda.CSVPreprocessing.placeholder_instructor = Instructor(instructor_firstName='John', instructor_lastName='Smith')
Definition at line 63 of file CSVPreprocessing.py.
remote
mavAgenda.CSVPreprocessing.remote = Campus(campus_name='R')
Definition at line 89 of file CSVPreprocessing.py.
reqs_path
string mavAgenda.CSVPreprocessing.reqs_path = '\\landing\\degreeData\\Course Requirements.csv'
Definition at line 16 of file CSVPreprocessing.py.
saturday
mavAgenda.CSVPreprocessing.saturday = Weekday(weekday_name='S')
Definition at line 77 of file CSVPreprocessing.py.
semesters
dictionary mavAgenda.CSVPreprocessing.semesters
Definition at line 93 of file CSVPreprocessing.py.
south
mavAgenda.CSVPreprocessing.south = Campus(campus_name='S')
Definition at line 85 of file CSVPreprocessing.py.
sunday
mavAgenda.CSVPreprocessing.sunday = Weekday(weekday_name='U')
Definition at line 79 of file CSVPreprocessing.py.
thursday
mavAgenda.CSVPreprocessing.thursday = Weekday(weekday_name='R')
Definition at line 73 of file CSVPreprocessing.py.
tuesday
mavAgenda.CSVPreprocessing.tuesday = Weekday(weekday_name='T')
Definition at line 69 of file CSVPreprocessing.py.
wednesday
mavAgenda.CSVPreprocessing.wednesday = Weekday(weekday_name='W')
Definition at line 71 of file CSVPreprocessing.py.