scrape Namespace Reference
Functions
def addReqSection (title, dept, num, desc, xx)
def main ()
Detailed Description
the name is a lie, this doesn't scrape anything
instead, it reads in a slightly formatted .txt
of matriculation data and organizes it prior to
inserting the values into a database...
so it's more of a data processing utility

(pdf > csv > txt > (x) > database > user's face)
                    ^
                we are here


last updated by ktsin 6/21/18
Function Documentation
addReqSection()
def scrape.addReqSection (title, dept, num, desc, xx)
Definition at line 69 of file scrape.py.
References main().
Referenced by main().
main()
def scrape.main ()
Definition at line 23 of file scrape.py.
References addReqSection().
Referenced by addReqSection().