mavAgenda.landing.views Namespace Reference
Functions
def checkOfferedSemester (course, ssf)
def checkPrereqsMet (conditions, classesTaken, currentSemester)
def checkReqsMet (reqTracker)
def combineEnforcedAndElectiveCourses (enforcedCourses, electiveCourses)
def countCourseTowardReqs (course, reqTracker)
def courseValid (course, classesTaken, semesterCourses, ssf)
def createSchedule (uID)
def createuser (request)
def emailFound (email)
def generateCheckBoxEntities (uID)
def generateConcentrationsDD ()
def generateDiplomaDD ()
def generateMajorDD ()
def generateMinorDD ()
def generateNewSemester (semester)
def generateNumCreditsDD (lo, hi, default)
def generateSemesterDD (default)
def generateYearDD (default)
def getCompletedByUser (uID)
def getCoursePrereqs (course)
def getCoursesForUser (uID)
def getDefaultPreferences (uID)
def getDegree (diploma, type, track)
def getDegreeReqs (degrees)
def getElectiveCourses (reqTracker)
def getEnforcedCourses (reqTracker)
def getNextSemesterTitle (ssf)
def getReqCourses (reqs)
def getSemesterByMonth (m)
def getUserByEmail (e)
def login (request)
def mandatePrereqsForEnforcedCourses (enfCourses)
def nextsemesterpreferences (request, pk)
def prefNumCreditsMet (uID, ssf, numberCreditsTaken)
def removeCoursesTaken (requiredClasses, classesTaken)
def removeUserCompletedEnteries (uID)
def saveClassesToUser (classesChecked, uID)
def schedule (request, pk)
def selectcourses (request, pk)
def setupReqTracker (uID)
def setupSchedule (uID)
def sortCoursesBySubNum (courses)
def tallyNumberCreditsTaken (courses)
def translateCourseInfoToCourse (reqClasses)
def updateReqTrackerForCompletedCourses (coursesCompleted, reqTracker)
Function Documentation
checkOfferedSemester()
def mavAgenda.landing.views.checkOfferedSemester (course, ssf)
@checkOfferedSemester determines if a given Course if offered during the current semester
@param course: the Course under test
@param ssf: the Spring, Summer, Fall, offering attribute of the Course
Definition at line 110 of file views.py.
Referenced by mavAgenda.landing.views.courseValid().
checkPrereqsMet()
def mavAgenda.landing.views.checkPrereqsMet (conditions, classesTaken, currentSemester)
@checkPrereqsMet determines if the User has met all Prereqs for a particular Course
@param coditions: a list of lists of Course (objects) corresponding to Prereqs for a given Course
@param classesTaken: a list of Course (objects) that the User has already completed
@parm scheduledClasses: a list of Course (objects) the scheduling algorithm has accounted for already
Definition at line 95 of file views.py.
Referenced by mavAgenda.landing.views.courseValid().
checkReqsMet()
def mavAgenda.landing.views.checkReqsMet (reqTracker)
@checkReqsMet returns True if all requirements for the user's desired degree have been met
@param reqTracker: the list of requirements needed for the user's desired degree
Definition at line 255 of file views.py.
Referenced by mavAgenda.landing.views.createSchedule().
combineEnforcedAndElectiveCourses()
def mavAgenda.landing.views.combineEnforcedAndElectiveCourses (enforcedCourses, electiveCourses)
@combineEnforcedAndElectiveCourses ensures there are no duplicates listed between the enforced and elective courses
@param enforcedCourses: a list of the course objects that are enforced
@param electiveCourses: a list of the courses objects that can be taken as electives
Definition at line 297 of file views.py.
Referenced by mavAgenda.landing.views.createSchedule().
countCourseTowardReqs()
def mavAgenda.landing.views.countCourseTowardReqs (course, reqTracker)
@countCourseTowardReqs credits the user for courses fulfilling their necessary requirements
@param course: the course to be counted for credit
@param reqTracker: the array of requirements needed for the user's desired degree
Definition at line 229 of file views.py.
Referenced by mavAgenda.landing.views.createSchedule(), and mavAgenda.landing.views.updateReqTrackerForCompletedCourses().
courseValid()
def mavAgenda.landing.views.courseValid (course, classesTaken, semesterCourses, ssf)
@checkCourseValid determines if a given Course can be taken during a given semester
@param course: the Course under test
@param classesTaken: a list of Course (objects) that the User has already completed
@parm scheduledClasses: a list of Course (objects) the scheduling algorithm has accounted for already
@param ssf: the Spring, Summer, Fall, offering attribute of the Course
Definition at line 126 of file views.py.
References mavAgenda.landing.views.checkOfferedSemester(), mavAgenda.landing.views.checkPrereqsMet(), and mavAgenda.landing.views.getCoursePrereqs().
Referenced by mavAgenda.landing.views.createSchedule().
createSchedule()
def mavAgenda.landing.views.createSchedule (uID)
@createSchedule generates semester-by-semester schedule for User's needed Courses according to Degree
@param uID: primary key associated with active user
Definition at line 323 of file views.py.
References mavAgenda.landing.views.checkReqsMet(), mavAgenda.landing.views.combineEnforcedAndElectiveCourses(), mavAgenda.landing.views.countCourseTowardReqs(), mavAgenda.landing.views.courseValid(), mavAgenda.landing.views.generateNewSemester(), mavAgenda.landing.views.getCompletedByUser(), mavAgenda.landing.views.getElectiveCourses(), mavAgenda.landing.views.getEnforcedCourses(), mavAgenda.landing.views.mandatePrereqsForEnforcedCourses(), mavAgenda.landing.views.prefNumCreditsMet(), mavAgenda.landing.views.setupReqTracker(), mavAgenda.landing.views.setupSchedule(), mavAgenda.landing.views.tallyNumberCreditsTaken(), and mavAgenda.landing.views.updateReqTrackerForCompletedCourses().
Referenced by mavAgenda.landing.views.schedule().
createuser()
def mavAgenda.landing.views.createuser (request)
@createuser send a request to render the createuser.html page
@param request: generates the response
Definition at line 641 of file views.py.
References mavAgenda.landing.views.emailFound(), mavAgenda.landing.views.generateConcentrationsDD(), mavAgenda.landing.views.generateDiplomaDD(), mavAgenda.landing.views.generateMajorDD(), mavAgenda.landing.views.generateMinorDD(), mavAgenda.landing.views.generateNumCreditsDD(), and mavAgenda.landing.views.getDegree().
emailFound()
def mavAgenda.landing.views.emailFound (email)
@emailFound provides feedback if the email is already in the User database table
@param email: email under test
Definition at line 543 of file views.py.
Referenced by mavAgenda.landing.views.createuser(), mavAgenda.landing.views.login(), and mavAgenda.landing.tests.test_logic.YourTestClass.test_emailFound().
generateCheckBoxEntities()
def mavAgenda.landing.views.generateCheckBoxEntities (uID)
@generateCheckBoxEntities creates a list of tuples of requirements, course names and numbers for the selectcourses page
@param uID: primary key corresponding to the active user
Definition at line 446 of file views.py.
References mavAgenda.landing.views.getDegreeReqs(), and mavAgenda.landing.views.getReqCourses().
Referenced by mavAgenda.landing.views.selectcourses().
generateConcentrationsDD()
def mavAgenda.landing.views.generateConcentrationsDD ()
@generateConcentrationsDD creates a list of possible concentrations for use on the createuser page
Definition at line 478 of file views.py.
Referenced by mavAgenda.landing.views.createuser(), and mavAgenda.landing.tests.test_logic.YourTestClass.test_generateConcentrationsDD().
generateDiplomaDD()
def mavAgenda.landing.views.generateDiplomaDD ()
@generateDiplomaDD creates a list of possible diplomas for use on the createuser page
Definition at line 489 of file views.py.
Referenced by mavAgenda.landing.views.createuser(), and mavAgenda.landing.tests.test_logic.YourTestClass.test_generateDiplomaDD().
generateMajorDD()
def mavAgenda.landing.views.generateMajorDD ()
@generateMajorDD creates a list of possible majors for use on the createuser page
Definition at line 456 of file views.py.
Referenced by mavAgenda.landing.views.createuser(), and mavAgenda.landing.tests.test_logic.YourTestClass.test_generateMajorDD().
generateMinorDD()
def mavAgenda.landing.views.generateMinorDD ()
@generateMinorDD creates a list of possible minors for use on the createuser page
Definition at line 467 of file views.py.
Referenced by mavAgenda.landing.views.createuser(), and mavAgenda.landing.tests.test_logic.YourTestClass.test_generateMinorDD().
generateNewSemester()
def mavAgenda.landing.views.generateNewSemester (semester)
@generateNewSemester creates a new logical semester
@param semester: previous semester list
Definition at line 157 of file views.py.
References mavAgenda.landing.views.getNextSemesterTitle().
Referenced by mavAgenda.landing.views.createSchedule(), mavAgenda.landing.tests.test_logic.YourTestClass.test_generate_new_semester(), and mavAgenda.landing.tests.test_logic.YourTestClass.test_is_full().
generateNumCreditsDD()
def mavAgenda.landing.views.generateNumCreditsDD (lo, hi, default)
@generateNumCreditsDD generates a dropdown for the number of credits the user can take
@param lo: the lowest number of credits possible
@param hi: the highest number of credits possible
@param default: the value of the number credits dropdown that ahould be selected automatically as a default
Definition at line 500 of file views.py.
Referenced by mavAgenda.landing.views.createuser(), and mavAgenda.landing.views.nextsemesterpreferences().
generateSemesterDD()
def mavAgenda.landing.views.generateSemesterDD (default)
@generateSemesterDD creates a list of upcoming semester for use on the createuser page
@parm default: the year value to be selected by default
Definition at line 530 of file views.py.
Referenced by mavAgenda.landing.views.nextsemesterpreferences().
generateYearDD()
def mavAgenda.landing.views.generateYearDD (default)
@generateYearDD creates a list of upcoming years for use on the createuser page
@parm default: the year value to be selected by default
Definition at line 516 of file views.py.
Referenced by mavAgenda.landing.views.nextsemesterpreferences().
getCompletedByUser()
def mavAgenda.landing.views.getCompletedByUser (uID)
@getCompletedByUser provides a list of Course (objects) the user has taken
@param uID: the primary key corresponding to the active user
Definition at line 47 of file views.py.
Referenced by mavAgenda.landing.views.createSchedule().
getCoursePrereqs()
def mavAgenda.landing.views.getCoursePrereqs (course)
@getCoursePrereqs returns a list of prereqs required for a course in the logical form:
    ex: [[courseA, courseB], [courseC, CourseD], [courseE]]
    where subset lists represent logical ORs and the larger list joined by logical ANDs.
    The above list would have prereqs: (courseA OR courseB) AND (courseC OR courseD) AND courseE
@param course: the Course under test
Definition at line 430 of file views.py.
Referenced by mavAgenda.landing.views.courseValid(), and mavAgenda.landing.views.mandatePrereqsForEnforcedCourses().
getCoursesForUser()
def mavAgenda.landing.views.getCoursesForUser (uID)
@getCoursesForUser provides a list of Course (objects) the user must complete for their respective Degree
@param uID: the primary key corresponding to the active user
Definition at line 58 of file views.py.
References mavAgenda.landing.views.getDegreeReqs(), and mavAgenda.landing.views.getReqCourses().
getDefaultPreferences()
def mavAgenda.landing.views.getDefaultPreferences (uID)
Definition at line 585 of file views.py.
References mavAgenda.landing.views.getNextSemesterTitle(), and mavAgenda.landing.views.getSemesterByMonth().
Referenced by mavAgenda.landing.views.nextsemesterpreferences().
getDegree()
def mavAgenda.landing.views.getDegree (diploma, type, track)
@getDegree searches the Degree table to find the Degree object with corresponding degree and major
@param d: degree attribute of Degree being searched for
@param m: major attribute of Degree being searched for
Definition at line 36 of file views.py.
Referenced by mavAgenda.landing.views.createuser(), and mavAgenda.landing.tests.test_logic.YourTestClass.test_getDegree().
getDegreeReqs()
def mavAgenda.landing.views.getDegreeReqs (degrees)
@getDegreeRegs returns a list of requirements for all degrees a user has selected
@param degrees: a list of degrees associated with the user
Definition at line 387 of file views.py.
Referenced by mavAgenda.landing.views.generateCheckBoxEntities(), mavAgenda.landing.views.getCoursesForUser(), and mavAgenda.landing.views.setupReqTracker().
getElectiveCourses()
def mavAgenda.landing.views.getElectiveCourses (reqTracker)
@getEnforcedCourses gets a list of courses that are enforced by requirements for the user's degree
@param reqTracker: a list of requirements the user must complete to receive their degree
Definition at line 202 of file views.py.
Referenced by mavAgenda.landing.views.createSchedule().
getEnforcedCourses()
def mavAgenda.landing.views.getEnforcedCourses (reqTracker)
@getEnforcedCourses gets a list of courses that are enforced by requirements for the user's degree
@param uID: user ID of the user requesting the enforced courses
@param reqTracker: a list of requirements the user must complete to receive their degree
Definition at line 187 of file views.py.
Referenced by mavAgenda.landing.views.createSchedule().
getNextSemesterTitle()
def mavAgenda.landing.views.getNextSemesterTitle (ssf)
@getNextSemseterTitle determines which semester will be the next semester (Spring, Summer, Fall)
@param ssf: the title of the current semester
Definition at line 142 of file views.py.
Referenced by mavAgenda.landing.views.generateNewSemester(), and mavAgenda.landing.views.getDefaultPreferences().
getReqCourses()
def mavAgenda.landing.views.getReqCourses (reqs)
@getReqCourses returns a list of courses (enforced and non-enforced) for a requirements related to a degree a user has selected
@param reqs: a list of requirements associated with the user's desired degree
Definition at line 412 of file views.py.
References mavAgenda.landing.views.sortCoursesBySubNum().
Referenced by mavAgenda.landing.views.generateCheckBoxEntities(), and mavAgenda.landing.views.getCoursesForUser().
getSemesterByMonth()
def mavAgenda.landing.views.getSemesterByMonth (m)
@getSemesterByMonthYear determines semester (Spring, Summer, Fall) according to current month
@param m: current month
Definition at line 23 of file views.py.
Referenced by mavAgenda.landing.views.getDefaultPreferences().
getUserByEmail()
def mavAgenda.landing.views.getUserByEmail (e)
@getUserByEmail searches the User table to find the User object with a corresponding email
@param e: the email being searched for
Definition at line 13 of file views.py.
Referenced by mavAgenda.landing.views.login(), and mavAgenda.landing.tests.test_logic.YourTestClass.test_getUserByEmail().
login()
def mavAgenda.landing.views.login (request)
@login send a request to render the login.html page
@param request: generates the response
Definition at line 622 of file views.py.
References mavAgenda.landing.views.emailFound(), and mavAgenda.landing.views.getUserByEmail().
mandatePrereqsForEnforcedCourses()
def mavAgenda.landing.views.mandatePrereqsForEnforcedCourses (enfCourses)
@mandatePrereqsForEnforcedCourses determine if there are classes needed as Prereqs for beginning enforced courses and if not accounted for, schedules them
@param enfCourses: a list of Course objects that a user is required to take according to their desired Degree Requirements
Definition at line 310 of file views.py.
References mavAgenda.landing.views.getCoursePrereqs().
Referenced by mavAgenda.landing.views.createSchedule().
nextsemesterpreferences()
def mavAgenda.landing.views.nextsemesterpreferences (request, pk)
@nextsemesterpreferences send a request to render the nextsemesterpreferences.html page
@param request: generates the response
@param pk: primary key corresponding to active user
Definition at line 748 of file views.py.
References mavAgenda.landing.views.generateNumCreditsDD(), mavAgenda.landing.views.generateSemesterDD(), mavAgenda.landing.views.generateYearDD(), and mavAgenda.landing.views.getDefaultPreferences().
prefNumCreditsMet()
def mavAgenda.landing.views.prefNumCreditsMet (uID, ssf, numberCreditsTaken)
@prefNumCreditsMet returns True if the number of credits scheduled for a semester is within the user's desired constraints
@param uID: the id of the user whose schedule is being processed
@param ssf: denotes the spring, summer, or fall semester
@numberCreditsTaken: the number of credits taken during the semester
Definition at line 277 of file views.py.
Referenced by mavAgenda.landing.views.createSchedule().
removeCoursesTaken()
def mavAgenda.landing.views.removeCoursesTaken (requiredClasses, classesTaken)
@removeCoursesTaken provides a list of Course (objects) the user must still take (required, but not completed classes)
@param requiredClasses: a list of Course (objects) required for the User's Degree
@param classesTaken: a list of Course (objects) that the User has already completed
Definition at line 83 of file views.py.
Referenced by mavAgenda.landing.tests.test_logic.YourTestClass.test_removeCoursesTaken().
removeUserCompletedEnteries()
def mavAgenda.landing.views.removeUserCompletedEnteries (uID)
@removeUserCompletedEntries updates database to remove courses completed from a particular user
@param uID: pk of the associated active user
Definition at line 574 of file views.py.
Referenced by mavAgenda.landing.views.selectcourses().
saveClassesToUser()
def mavAgenda.landing.views.saveClassesToUser (classesChecked, uID)
@saveClassesToUser updates database with a list of the user has taken
@param classesChecked: list of courses the user specified as having taken
@param uID: pk of the associated active user
Definition at line 555 of file views.py.
Referenced by mavAgenda.landing.views.selectcourses().
schedule()
def mavAgenda.landing.views.schedule (request, pk)
@schedule send a request to render the schedule.html page
@param request: generates the response
@param pk: primary key corresponding to active user
Definition at line 774 of file views.py.
References mavAgenda.landing.views.createSchedule().
selectcourses()
def mavAgenda.landing.views.selectcourses (request, pk)
@selectcourses send a request to render the selectcourses.html page
@param request: generates the response
@param pk: primary key corresponding to active user
Definition at line 732 of file views.py.
References mavAgenda.landing.views.generateCheckBoxEntities(), mavAgenda.landing.views.removeUserCompletedEnteries(), and mavAgenda.landing.views.saveClassesToUser().
setupReqTracker()
def mavAgenda.landing.views.setupReqTracker (uID)
@setupReqTracker sets up a list of requirements and progress tracking values (i.e., credits needed)
@param uID: user ID of the user requesting the req tracker; needed to determine requirements needed
Definition at line 172 of file views.py.
References mavAgenda.landing.views.getDegreeReqs().
Referenced by mavAgenda.landing.views.createSchedule().
setupSchedule()
def mavAgenda.landing.views.setupSchedule (uID)
@setupSchedule creates a template for generating an schedule
@param uID: user ID of the user requesting the schedule
Definition at line 216 of file views.py.
Referenced by mavAgenda.landing.views.createSchedule().
sortCoursesBySubNum()
def mavAgenda.landing.views.sortCoursesBySubNum (courses)
@sortCoursesBySubNum takes a list of course information and sorts them course information according to subject and number
@param courses: list of courses information pieces that need to be stored for the checkbox page
Definition at line 399 of file views.py.
Referenced by mavAgenda.landing.views.getReqCourses().
tallyNumberCreditsTaken()
def mavAgenda.landing.views.tallyNumberCreditsTaken (courses)
@tallyNumberCreditsTaken returns the total number of credits scheduled for a semester
@param courses: the list of Course objects scheduled for the semester
Definition at line 267 of file views.py.
Referenced by mavAgenda.landing.views.createSchedule().
translateCourseInfoToCourse()
def mavAgenda.landing.views.translateCourseInfoToCourse (reqClasses)
@translateCourseInfoToCourse translate the list of course information (from getCoursesForUser) into a list of Course objects
@param reqClasses: a list of course information pieces
Definition at line 73 of file views.py.
updateReqTrackerForCompletedCourses()
def mavAgenda.landing.views.updateReqTrackerForCompletedCourses (coursesCompleted, reqTracker)
@updateReqTrackerForCompletedCourses provides credit to a user for completing a number of courses
@param course: the courses to be counted for credit toward their requirements
@param reqTracker: the array of requirements needed for the user's desired degree
Definition at line 246 of file views.py.
References mavAgenda.landing.views.countCourseTowardReqs().
Referenced by mavAgenda.landing.views.createSchedule().